version: '3'
services:
  imageprocessor-streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imageprocessor-streamlit
    volumes:
      - ./logs:/app/logs:rw
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: imageprocessor.wanglab.science
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: imageprocessor.wanglab.science
      LETSENCRYPT_EMAIL: mwang87@gmail.com

networks:
  nginx-net:
    external:
      name: nginx-net